export const sioV5JsonSchema = {
  type: "object",
  properties: {
    score: { type: "number", minimum: 0, maximum: 100 },
    statement: { type: "string" },
    overallCommentPositive: { type: "array", items: { type: "string" } },
    overallCommentNegative: { type: "array", items: { type: "string" } },
    websiteSummary: {
      type: "object",
      properties: {
        summary: { type: "string" },
        summaryComment: { type: "string" },
        problems: {
          type: "object",
          properties: {
            currents: { type: "array", items: { type: "string" } },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
          },
          required: ["currents", "positiveComments", "negativeComments"],
        },
        outcomes: {
          type: "object",
          properties: {
            currents: { type: "array", items: { type: "string" } },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
          },
          required: ["currents", "positiveComments", "negativeComments"],
        },
        solutions: {
          type: "object",
          properties: {
            currents: { type: "array", items: { type: "string" } },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
          },
          required: ["currents", "positiveComments", "negativeComments"],
        },
        features: {
          type: "object",
          properties: {
            currents: { type: "array", items: { type: "string" } },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
          },
          required: ["currents", "positiveComments", "negativeComments"],
        },
        isPositioningClear: { type: "boolean" },
        isMessagingClear: { type: "boolean" },
        areUsersLeftGuessing: { type: "boolean" },
      },
      required: [
        "summary",
        "problems",
        "outcomes",
        "solutions",
        "features",
        "isPositioningClear",
        "isMessagingClear",
        "areUsersLeftGuessing",
      ],
    },
    firstImpression: {
      type: "object",
      properties: {
        score: { type: "number", minimum: 0, maximum: 100 },
        statement: { type: "string" },
        recommendation: { type: "array", items: { type: "string" } },
        overallCommentPositive: { type: "array", items: { type: "string" } },
        overallCommentNegative: { type: "array", items: { type: "string" } },
        headline: {
          type: "object",
          properties: {
            statement: { type: "string" },
            current: { type: "string" },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
            recommendation: { type: "array", items: { type: "string" } },
            suggested: { type: "array", items: { type: "string" } },
          },
          required: [
            "statement",
            "current",
            "positiveComments",
            "negativeComments",
            "recommendation",
            "suggested",
          ],
        },
        subheadline: {
          type: "object",
          properties: {
            statement: { type: "string" },
            current: { type: "string" },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
            recommendation: { type: "array", items: { type: "string" } },
            suggested: { type: "array", items: { type: "string" } },
          },
          required: [
            "statement",
            "current",
            "positiveComments",
            "negativeComments",
            "recommendation",
            "suggested",
          ],
        },
        cta: {
          type: "object",
          properties: {
            statement: { type: "string" },
            current: { type: "string" },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
            recommendation: { type: "array", items: { type: "string" } },
            suggested: { type: "array", items: { type: "string" } },
          },
          required: [
            "statement",
            "current",
            "positiveComments",
            "negativeComments",
            "recommendation",
            "suggested",
          ],
        },
      },
      required: [
        "score",
        "statement",
        "recommendation",
        "overallCommentPositive",
        "overallCommentNegative",
        "headline",
        "subheadline",
        "cta",
      ],
    },
    positioning: {
      type: "object",
      properties: {
        score: { type: "number", minimum: 0, maximum: 100 },
        statement: { type: "string" },
        recommendation: { type: "array", items: { type: "string" } },
        overallCommentPositive: { type: "array", items: { type: "string" } },
        overallCommentNegative: { type: "array", items: { type: "string" } },
        summary: {
          type: "object",
          properties: {
            current: { type: "string" },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
            recommendation: { type: "array", items: { type: "string" } },
            suggested: { type: "array", items: { type: "string" } },
          },
          required: [
            "current",
            "positiveComments",
            "negativeComments",
            "recommendation",
            "suggested",
          ],
        },
        subMetrics: {
          type: "object",
          properties: {
            categoryOwnership: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
            uniqueValueProp: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
            competitiveDiff: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
            targetAudience: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
            problemSolutionFit: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
            messagingConsistency: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
              ],
            },
          },
          required: [
            "categoryOwnership",
            "uniqueValueProp",
            "competitiveDiff",
            "targetAudience",
            "problemSolutionFit",
            "messagingConsistency",
          ],
        },
      },
      required: [
        "score",
        "statement",
        "recommendation",
        "overallCommentPositive",
        "overallCommentNegative",
        "summary",
        "subMetrics",
      ],
    },
    clarity: {
      type: "object",
      properties: {
        score: { type: "number", minimum: 0, maximum: 100 },
        statement: { type: "string" },
        recommendation: { type: "array", items: { type: "string" } },
        overallCommentPositive: { type: "array", items: { type: "string" } },
        overallCommentNegative: { type: "array", items: { type: "string" } },
        summary: {
          type: "object",
          properties: {
            current: { type: "string" },
            positiveComments: { type: "array", items: { type: "string" } },
            negativeComments: { type: "array", items: { type: "string" } },
            recommendation: { type: "array", items: { type: "string" } },
            suggested: { type: "array", items: { type: "string" } },
          },
          required: [
            "current",
            "positiveComments",
            "negativeComments",
            "recommendation",
            "suggested",
          ],
        },
        unclearSentences: {
          type: "array",
          items: {
            type: "object",
            properties: {
              text: { type: "string" },
              issue: { type: "string" },
              fix: { type: "string" },
            },
            required: ["text", "issue", "fix"],
          },
        },
        subMetrics: {
          type: "object",
          properties: {
            headlineClarity: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
            valueProposition: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
            featureBenefitMapping: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
            visualHierarchy: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
            ctaClarity: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
            proofPlacement: {
              type: "object",
              properties: {
                statement: { type: "string" },
                score: { type: "number", minimum: 0, maximum: 100 },
                current: { type: "string" },
                positiveComments: { type: "array", items: { type: "string" } },
                negativeComments: { type: "array", items: { type: "string" } },
                recommendation: { type: "array", items: { type: "string" } },
                suggested: { type: "array", items: { type: "string" } },
                unclearTexts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      text: { type: "string" },
                      issue: { type: "string" },
                      fix: { type: "string" },
                    },
                    required: ["text", "issue", "fix"],
                  },
                },
              },
              required: [
                "statement",
                "score",
                "current",
                "positiveComments",
                "negativeComments",
                "recommendation",
                "suggested",
                "unclearTexts",
              ],
            },
          },
          required: [
            "headlineClarity",
            "valueProposition",
            "featureBenefitMapping",
            "visualHierarchy",
            "ctaClarity",
            "proofPlacement",
          ],
        },
      },
      required: [
        "score",
        "statement",
        "recommendation",
        "overallCommentPositive",
        "overallCommentNegative",
        "summary",
        "unclearSentences",
        "subMetrics",
      ],
    },
    aeo: {
      type: "object",
      properties: {
        score: { type: "number", minimum: 0, maximum: 100 },
        statement: { type: "string" },
        aiPresence: {
          type: "object",
          properties: {
            isPresent: { type: "boolean" },
            engines: { type: "array", items: { type: "string" } },
            comment: { type: "string" },
          },
          required: ["isPresent", "engines", "comment"],
        },
        recommendations: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["score", "statement", "aiPresence", "recommendations"],
    },
  },
  required: [
    "score",
    "statement",
    "overallCommentPositive",
    "overallCommentNegative",
    "websiteSummary",
    "firstImpression",
    "positioning",
    "clarity",
    "aeo",
  ],
};
